### ISSUE TITLE
Weighting explanation

### ISSUE THREAD

**Issue by withanhdammit** [Mazn1191/Arduino-Borealis#1]
Thanks for the code!

I'm trying to understand how the weighting works.  For example, is {10, 10, 10, 9, 9} functionally any different than {2, 2, 2, 1, 1}?

Would you please provide an explanation of how the weighting works?

Thanks!

**Comment by Mazn1191** [comment]
Hello withanhdammit,

simply put, a color with twice the weighting of the other colors is twice as likely to be selected. So the weighting number of a color alone doesn't say much. What matters is the ratio to the weighting of the other colors.

In you second example colors 1-3 are twice as likely (100% more likely) to be choosen as colors 4 and 5. 
In your first example colors 1-3 are only marginally more likely (10% more likely) to be choosen compared to colors 4 and 5.

This is how the function `byte getWeightedColor(byte weighting)` does it:

It sums up all the weights of a given preset and gives every color its "slot".
Lets see how this works with you first example:

    |----------|----------|----------|---------|---------|
         c1         c2         c3        c4        c5

Every dash here is one "unit" of weight, so c1-3 have slightly larger slots.
Now a random dash out of all of them is picked, and to whichever color it belongs, that color is choosen.

So `{2, 2, 2, 1, 1}` would be functionally identical to for example `{4, 4, 4, 2, 2}`, since all the ratios are the same.

**Comment by withanhdammit** [comment]
Thank you so much for the explanation!
